### ISSUE TITLE
Vapoursynth support?

### ISSUE THREAD

**Issue by Selur** [Asd-g/AviSynthPlus-grayworld#1]
Would be nice if this filter also could be used in Vapoursynth.

**Comment by Asd-g** [comment]
Ok.

**Comment by Asd-g** [comment]
Try the latest release.

**Comment by Selur** [comment]
Thanks! Seems to work fine. Will do some more test after work today and report back if an unexpected issue arises. 👍

**Comment by kedaitinh12** [comment]
> Try the latest release.

I only seen old ver in latest released

**Comment by Asd-g** [comment]
Download it again. It works with both avs and vs.

**Comment by kedaitinh12** [comment]
Thanks
